accepted-claims-set = {​
  &(ce.evidence-triples: 0) => [ + reference-triple-record ]​
  ? &(ce.identity-triples: 1) => [ + identity-triple-record ]​
  ? &(ce.dependency-triples: 2) => [ + domain-dependency-triple-record ]
  ? &(ce.domain-membership-triples: 3) => [ + domain-membership-triple-record ]
  ? &(ce.coswid-triples: 4) => [ + ev-coswid-triple-record ]
  * $$ev-triples-map-extension​
}
