accepted-claims-set = {
  &(evidence-triples: 0) => [ + reference-triple-record ]
  ? &(identity-triples: 2) => [ + identity-triple-record ]
  ? &(coswid-triples: 6) => [ + ev-coswid-triple-record ]
  * $$triples-map-extension
}
