conditional-endorsement-series-triple-record = [
  condition: [
    environment: environment-map,
    ? claims-list: [ + measurement-map ],
    ? authorized-by: [ + $crypto-key-type-choice ]
  ]
  series: [ + conditional-series-record ]
]
