$$triples-map-extension //= (
  &(conditional-reference-series-triples: 8) => 
    [ + conditional-reference-series-triple-record ]
)

conditional-reference-series-triple-record = [
  ; triple subject
  [ environment-map,
    measurement-map ; initial reference values
  ] 
  ; triple object - series of conditional values
  [ + conditional-series-record ]
]
 
conditional-series-record = [
    measurement-values-map ; reference values
  ? measurement-values-map ; endorsed values
]
