conditional-series-record = [
  ; reference values to be matched against evidence in each mkey
  refv: [ + measurement-map ]
  ; endorsed values that apply in case revf matches
  endv: [ + mkeyvalue-pair ]
]
