$$triples-map-extension //= (
  &(conditional-reference-series-triples: 8) => 
    [ + conditional-reference-series-triple-record ]
)

conditional-reference-series-triple-record = [
  ; triple subject
  [ environment-map,
    measurement-map / measurement-values-map ; initial reference values
  ] 
  ; triple object
  [ + reference-endorsed-record ]
]
 
reference-endorsed-record = [
    measurement-map / measurement-values-map ; addit'l reference values
  ? measurement-map / measurement-values-map ; endorsed values
]
