corim = tagged-concise-rim-type-choice / $concise-rim-type-choice

$concise-rim-type-choice /= tagged-corim-map
$concise-rim-type-choice /= tagged-signed-corim
$concise-rim-type-choice /= COSE-Sign1-corim
