COSE-Sign1-corim = [
  protected: bstr .cbor protected-corim-header-map
  unprotected: unprotected-corim-header-map
  payload: bstr .cbor tagged-unsigned-corim-map / hash-envelope-digest-payload / nil
  signature: bstr
]

hash-envelope-digest-payload = bstr