COSE-Sign-corim = [
  protected: bstr .size 0
  unprotected: {},
  payload: bstr .cbor tagged-unsigned-corim-map /
                      hash-envelope-digest /
                      nil
  signature: [2* signature-structure]
]

