COSE-Sign-corim = [
  protected: bstr .size 0,
  unprotected: empty_body_unprotected_header
  payload: bstr .cbor tagged-unsigned-corim-map /
                      hash-envelope-digest /
                      nil
  signatures: [2* signature_structure]
]

hash-envelope-digest = bstr

empty_body_unprotected_header = {}