
component-id = [
  name: text
  ? version: $version-scheme
]

eat-measured-component = {
  &(id: 1) => component-id
  &(measurement: 2) => digests-type
  ? &(signers: 3) => [ + bytes ]
  ? &(flags: 4) => bytes .size 4
}
