flags-map = {
  ? &(configured: 0) => bool
  ? &(secure: 1) => bool
  ? &(recovery: 2) => bool
  ? &(debug: 3) => bool
  ? &(replay-protected: 4) => bool
  ? &(integrity-protected: 5) => bool
  ? &(runtime-meas: 6) => bool
  ? &(immutable: 7) => bool
  ? &(tcb: 8) => bool
  * $$flags-map-extension
}
