$instance-id-type-choice /= tagged-ueid-type
$instance-id-type-choice /= tagged-uuid-type
$instance-id-type-choice /= $crypto-key-type-choice
$instance-id-type-choice /= tagged-bytes
$instance-id-type-choice /= instance-slot-store-type
$instance-id-type-choice /= instance-slot-use-type
