D-ECT = {
  ? domain-id: domain-type
  ? authority: [ + $crypto-key-type-choice ]
  ? children: [ + environment-map ]
  ? kind: kind
  ? profile: $profile-type-choice
}

kind = &(
  member: 0
  trustee: 1
)
