ev = [ + ev-item ]

ev-item = {
  condition: [ + ECT ]
  addition: [ + ECT ]
}

evs = [ + evs-item ]

evs-item = {
  condition: [ + ECT ]
  series: [ + series-item ]
}

series-item = [
  selection: [ + ECT ]
  addition: [ + ECT ]
]
