evs = [ + evs-item ]

evs-item = {
  condition: Endorsement-condition-ECT
  series: [ + series-item ]
}

series-item = [
  selection: [ + Endorsement-selection-ECT ]
  addition: [ + Endorsement-addition-ECT ]
]
