Key-condition-ECT = ({
  environment: environment-map
  authority: [ + $crypto-key-type-choice ]
  ? profile: $profile-type-choice
  ? key-id: $measured-element-type-choice
  key-list: [ + $crypto-key-type-choice ]
  key-type: key-type
}) .within K-ECT
