E-ECT = {
  ECT-common
  ? element-list: [ + element-map ]
  ? cmtype: cm-type
}

element-map = {
  ? element-id: $measured-element-type-choice
  element-claims: measurement-values-map
}

cm-type = &(
  reference-values: 0
  endorsements: 1
  evidence: 2
)
