Reference-Value-addition-ECT = ({
  environment: environment-map
  element-list: [ + element-map ]
  authority: [ + $crypto-key-type-choice ]
  cmtype: 0
  ? profile: $profile-type-choice
}) .within E-ECT
