ECT = {
  ? &(environment: 0) => environment-map
  ? &(element-list: 1) => [ + element-map ]
  ? &(authority: 2) => [ + $crypto-key-type-choice ]
  &(cmtype: 3) => uint .bits cm-type
  ? &(profile: 4) => $profile-type-choice
}

element-map = {
  ? &(element-id: 0) => $measured-element-type-choice
  &(element-claims: 1) => measurement-values-map
}

cm-type =  &(
  reference-values: 0
  endorsements: 1
  evidence: 2
  attestation-results: 3
  verifier: 4
  policy: 5
)
