linear-privlevel-type-choice /= signed-integer-range-type-choice
signed-integer-range-type-choice = int / tagged-int-range
int-range = [min: opt-int, max: opt-int]
tagged-int-range = #6.564(int-range)
opt-int = int / null
