linear-privlevel-type-choice /= signed-integer-range-type-choice
signed-integer-range-type-choice = int-eq / int-range / tagged-int-eq / tagged-int-range
int-eq = int
int-range = [min: inf-int, max: inf-int]
tagged-int-eq = #6.564(int-eq)
tagged-int-range = #6.565(int-range)
inf-int = -Infinity / int / Infinity

