measurement-map = {
  ? &(mkey: 0) => $measured-element-type-choice
  ? &(mval: 1) => measurement-values-map
  ? &(authorized-by: 2) => [ + $crypto-key-type-choice ]
  ? &(mkeyvalues: 3) => [ + mkeyvalue-pair ]
}
