multi-conditional-endorsement-triple-record = [
  cond: [ + stateful-environment-record], ; a set of stateful environments to be matched against evidence or endorsements
  end:  [ + stateful-environment-record]  ; a set of endorsements to be accepted upon matching the subject `cond`
]
