; protected header map MUST contain at least one of corim-meta (8) or CWT-Claims (15)
protected-corim-header-map =
  {
    &(alg: 1) => int,
    &(content-type: 3) => "application/rim+cbor",
    meta,
    * cose-label => cose-value
  }

meta = ((
        corim-meta-fragment,
        ? cwt-claims-fragment,
      ) // cwt-claims-fragment)

corim-meta-fragment = (&(corim-meta: 8) => bstr .cbor corim-meta-map)
cwt-claims-fragment = (&(CWT-Claims: 15) => cwt-claims)