raw-integral-type-choice /= integral / tagged-integral-range
integral-range = [min: opt-integral, max: opt-integral]
tagged-integral-range = #6.564(integral-range)
integral = int / #6.2(bytes) / #6.3(bytes)
opt-integral = integral / null
