; 
; reference-endorsed-triple 
; 
;
; Triples map extension
;
 $$triples-map-extension //= (
  &(reference-endorsed-triples: 7) => [ + reference-endorsed-triple-record]
)

;
; Triple subject: Target Environment (TE)
; Triple object: refvals (RV) + endvals (EV)
; Triple predicate: When TE matches evidence RV claims are accepted 
;                   and when RV claims are accepted EV claims are also accepted
;
reference-endorsed-triple-record = [
  environment-map ; target environment
  [ + reference-endorsed-map ] ; reference values with endorsed values
]
; Multiple instances of reference-endorsed-map are positionally significant
; The map at position 0 will always be at position 0 and so forth for all positions 0 - n

reference-endorsed-map = {
  &(refvals: 0) => measurement-map / measurement-values-map, ; reference values
  &(endvals: 1) => measurement-map / measurement-values-map ; conditionally endorsed values
}
; The Verifier verifies refvals are within Evidence, upon successful verification, endvals are accepted
