x-ref-endors-triple-record = [
&(subj: 0) => $subject-type-choice
& (mval: 1) => [+measurement-values-map]
&(reason: 2) => $reason-type-choice
]

$reason-type-choice /= obsolete
$reason-type-choice /= insecure
