draft-ietf-rats-corim.xml: cddl/corim.cddl
draft-ietf-rats-corim.xml: cddl/corim-map.cddl
draft-ietf-rats-corim.xml: cddl/tagged-unsigned-corim-map.cddl
draft-ietf-rats-corim.xml: cddl/corim-id-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/concise-tag-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/corim-locator-map.cddl
draft-ietf-rats-corim.xml: cddl/profile-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/corim-entity-map.cddl
draft-ietf-rats-corim.xml: cddl/corim-role-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/signed-corim.cddl
draft-ietf-rats-corim.xml: cddl/cose-sign1-corim.cddl
draft-ietf-rats-corim.xml: cddl/protected-corim-header-map.cddl
draft-ietf-rats-corim.xml: cddl/corim-meta-map.cddl
draft-ietf-rats-corim.xml: cddl/corim-signer-map.cddl
draft-ietf-rats-corim.xml: cddl/unprotected-corim-header-map.cddl
draft-ietf-rats-corim.xml: cddl/cmw-corim-collection.cddl
draft-ietf-rats-corim.xml: cddl/examples/cmw-corim-collection.diag
draft-ietf-rats-corim.xml: cddl/concise-mid-tag.cddl
draft-ietf-rats-corim.xml: cddl/tag-identity-map.cddl
draft-ietf-rats-corim.xml: cddl/tag-id-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/tag-version-type.cddl
draft-ietf-rats-corim.xml: cddl/comid-entity-map.cddl
draft-ietf-rats-corim.xml: cddl/comid-role-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/linked-tag-map.cddl
draft-ietf-rats-corim.xml: cddl/tag-rel-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/triples-map.cddl
draft-ietf-rats-corim.xml: cddl/environment-map.cddl
draft-ietf-rats-corim.xml: cddl/class-map.cddl
draft-ietf-rats-corim.xml: cddl/class-id-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/instance-id-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/group-id-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/measurement-map.cddl
draft-ietf-rats-corim.xml: cddl/measured-element-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/measurement-values-map.cddl
draft-ietf-rats-corim.xml: cddl/version-map.cddl
draft-ietf-rats-corim.xml: cddl/svn-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/flags-map.cddl
draft-ietf-rats-corim.xml: cddl/raw-value.cddl
draft-ietf-rats-corim.xml: cddl/tagged-masked-raw-value.cddl
draft-ietf-rats-corim.xml: cddl/ip-addr-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/mac-addr-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/crypto-key-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/integrity-registers.cddl
draft-ietf-rats-corim.xml: cddl/raw-int-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/domain-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/reference-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/endorsed-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/conditional-endorsement-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/stateful-environment-record.cddl
draft-ietf-rats-corim.xml: cddl/conditional-endorsement-series-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/conditional-series-record.cddl
draft-ietf-rats-corim.xml: cddl/identity-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/attest-key-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/domain-dependency-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/domain-membership-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/coswid-triple-record.cddl
draft-ietf-rats-corim.xml: cddl/concise-tl-tag.cddl
draft-ietf-rats-corim.xml: cddl/non-empty.cddl
draft-ietf-rats-corim.xml: cddl/entity-map.cddl
draft-ietf-rats-corim.xml: cddl/entity-name-type-choice.cddl
draft-ietf-rats-corim.xml: cddl/validity-map.cddl
draft-ietf-rats-corim.xml: cddl/uuid.cddl
draft-ietf-rats-corim.xml: cddl/ueid.cddl
draft-ietf-rats-corim.xml: cddl/oid.cddl
draft-ietf-rats-corim.xml: cddl/digest.cddl
draft-ietf-rats-corim.xml: cddl/tagged-bytes.cddl
draft-ietf-rats-corim.xml: cddl/intrep-ect.cddl
draft-ietf-rats-corim.xml: cddl/intrep-key.cddl
draft-ietf-rats-corim.xml: cddl/intrep-ae.cddl
draft-ietf-rats-corim.xml: cddl/intrep-rv.cddl
draft-ietf-rats-corim.xml: cddl/intrep-ev.cddl
draft-ietf-rats-corim.xml: cddl/intrep-policy.cddl
draft-ietf-rats-corim.xml: cddl/intrep-ar.cddl
draft-ietf-rats-corim.xml: cddl/intrep-acs.cddl
draft-ietf-rats-corim.xml: cddl/intrep-ars.cddl
draft-ietf-rats-corim.xml: cddl/corim-autogen.cddl
